#!/bin/sh

set -e

fail()
{
    echo 2>&1 "$*"
    exit 1
}

test_output()
(
    expected=$1
    shift
    [ "$(./rpn.py $*)" = "$expected" ] || fail "$expected != rpn $*"
    [ "$(./rpn.py "$*")" = "$expected" ] || fail "$expected != rpn \"$*\""
)

test_output 3 1 2+
test_output 6 1 2 3s
test_output 6 1 2 3p
test_output 10 1 2 3 4s
test_output 24 1 2 3 4p
test_output 8:7 16:15 '15:14*'
test_output 4:3 9:8 10:9 16:15p
test_output 4:3 9 8/ 10 9/ 16 15/p
test_output 4:3 9 8/10 9/16 15/p
test_output 225:224 15:14 16:15/
test_output 225:224 16:15 15:14r/
test_output 1.5 3:2f
test_output -3 3-
test_output 123 1.234 100*i
test_output 2 '2qd*0.000000001+i'
test_output 2 '2vd*0.000000001+i'
test_output 5 1.1 1.2 1.3 1.4 1.5mis
test_output 702 3 '2/2l1200*0.5+i'
test_output 702 3:2 '2l1200*0.5+i'
test_output 7 2 3 5 7m2lm0 5- 2 2 0 '1-m*s1200*i'
test_output 225 2 3 5 7m2lm0 5- 2 2 0 '1-m*s2r^224*0.0001+i'
test_output 33 1 3%i
test_output '1 2 3 4' 1 2 3 4m
test_output '1 2 3 4' 1 4tm
test_output '6 15' 1 2 3m4 5 6msrsrm
test_output '6 15' 1 2 3m4 5 6srsrm
test_output 0 s
test_output 1 p
test_output 10 1 10 tc
test_output 10 1 10 tmc
test_output 65 1 10 tcmjs
test_output 0 c
test_output 50 100tmc/s
